data_path: "../../datasets/MVTEC"
distillType: dbfad 
obj: wood
phase: train
save_path: "./results"
TrainingData:
  epochs: 50
  batch_size: 8
  lr: 0.0004
  img_size: 224
  crop_size: 224
  norm: True # normalize features before loss calculation
